services:
  pass-secure:
    build: .
    container_name: pass-secure
    ports:
      - "3000:${PORT}"
    networks:
      - network
    depends_on:
      database:
          condition: service_healthy
    volumes:
      - ./rsa:/app/rsa
    environment:
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: database
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      PORT: ${PORT}
  database:
    image: postgres:latest
    container_name: database
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:${DATABASE_PORT}"
    networks:
      - network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}"]
      interval: 5s
      retries: 5
      start_period: 5s

networks:
  network:
